services:
  postgres:
    image: postgres:15
    container_name: wedding-planner-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres_test:
    image: postgres:15
    container_name: wedding-planner-postgres-test
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wedding_app_test
    ports:
      - "5433:5432"
    volumes:
      - ./schema-dump.sql:/docker-entrypoint-initdb.d/10-schema.sql
      - postgres_test_data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  postgres_data:
  postgres_test_data:
  minio_data: