services:
  postgres_17:
    image: postgres:17
    container_name: wedding-planner-postgres-17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_17_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:17
    container_name: wedding-planner-postgres-test
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  postgres_17_data:
  postgres_test_data:
  minio_data: