/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Guests {
  coupleSide: CoupleSide;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<number>;
  isInvited: Generated<boolean>;
  modifiedAt: Timestamp | null;
  name: string;
  phoneNumber: string;
  userId: number;
}

export interface Photos {
  bucketName: BucketName;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  id: Generated<number>;
  main: Generated<boolean | null>;
  placeId: number;
}

export interface PhotosVariants {
  id: Generated<number>;
  objectKey: string;
  photoId: number;
  ratio: number;
  variant: string;
}

export interface PlaceFilter {
  id: Generated<number>;
  isFavorite: Generated<boolean | null>;
  isPicked: Generated<boolean | null>;
  placeId: number;
  userId: number;
}

export interface Places {
  city: string | null;
  country: CountryCode;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  description: string | null;
  facebook: string | null;
  googleId: string | null;
  id: Generated<number>;
  instagram: string | null;
  isPublished: Generated<boolean>;
  lat: number | null;
  lng: number | null;
  maxPrice: Numeric | null;
  minPrice: Numeric | null;
  modifiedAt: Timestamp | null;
  name: string | null;
  phoneNumber: string | null;
  postalCode: string | null;
  priceType: PriceType;
  promotionBeginsAt: Timestamp | null;
  promotionEndsAt: Timestamp | null;
  saleLabel: SaleLabel;
  salePercentage: Numeric | null;
  step: Categories;
  streetName: string | null;
  tiktok: string | null;
  userId: Generated<number>;
  website: string | null;
}

export interface Plans {
  id: Generated<number>;
  ignoredSteps: string | null;
  userId: number | null;
  weddingDate: Timestamp | null;
}

export interface Promotions {
  id: Generated<number>;
  placeId: number;
  price: Numeric | null;
  priceInPurchasedCurrency: Numeric | null;
  productId: string | null;
  purchasedAt: Timestamp;
}

export interface Users {
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  email: string;
  firstName: string;
  id: Generated<number>;
  lastName: string;
  password: string;
  refreshToken: string | null;
  role: Role;
  updatedAt: Timestamp | null;
}

export interface DB {
  guests: Guests;
  photos: Photos;
  photosVariants: PhotosVariants;
  placeFilter: PlaceFilter;
  places: Places;
  plans: Plans;
  promotions: Promotions;
  users: Users;
}
