export enum Categories {
  Host = 'Host',
  Dress = 'Dress',
  Suit = 'Suit',
  Photographer = 'Photographer',
  Car = 'Car',
  Dj = 'Dj',
  MakeUpArtist = 'MakeUpArtist',
  Salon = 'Salon',
  Florist = 'Florist',
  Decorator = 'Decorator',
  Catering = 'Catering',
  DancingCourse = 'DancingCourse',
  Giveaway = 'Giveaway',
  Procession = 'Procession',
  Performer = 'Performer',
  Jewelry = 'Jewelry',
  Perfume = 'Perfume',
  Shower = 'Shower',
  Clinic = 'Clinic',
  Firework = 'Firework',
  Miscellaneous = 'Miscellaneous',
}
