export enum WeddingSteps {
  Host = 'Host',
  Dress = 'Dress',
  Photographer = 'Photographer',
  Dj = 'Dj',
  MakeUpArtist = 'MakeUpArtist',
  Decorator = 'Decorator',
  Catering = 'Catering',
  DancingCourse = 'DancingCourse',
  Aarada = 'Aarada',
  Car = 'Car',
  Giveaways = 'Giveaways',
  MusiciansAndPerformers = 'MusiciansAndPerformers',
  Jewelry = 'Jewelry',
  Perfumes = 'Perfumes',
  Hammam = 'Hammam',
  CosmeticClinics = 'CosmeticClinics',
  Fireworks = 'Fireworks',
  Extra = 'Extra',
}
