export enum WeddingSteps {
  Date = 'Date',
  Host = 'Host',
  Dress = 'Dress',
  Photographer = 'Photographer',
  Dj = 'Dj',
  MakeUpArtist = 'MakeUpArtist',
  Decorator = 'Decorator',
  Catering = 'Catering',
  Coordinator = 'Coordinator',
  DancingCourse = 'DancingCourse',
  Aarada = 'Aarada',
  Car = 'Car',
  HotelAfterWedding = 'HotelAfterWedding',
  Giveaways = 'Giveaways',
  MusiciansAndPerformers = 'MusiciansAndPerformers',
  Jewelry = 'Jewelry',
  Perfumes = 'Perfumes',
  Hammam = 'Hammam',
  CosmeticClinics = 'CosmeticClinics',
  ExtraDecorations = 'ExtraDecorations',
}
