name : test & migrate

on:
  push:
  branches:
      - live
      - staging
jobs:

  test:
    runs-on: ubuntu-latest
  
  steps:
    - name: Checkout node
      uses: actions/checkout@v5

    - name: setup node
      uses: actions/setup-node@84
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run TypeScript Checks
      run: npx tsc --noEmit

    - name : Running Tests
      run : npm run jest 
      