name: Deploy to Railway

on:
  push:
    branches:
      - live
      - staging

jobs:

  deploy:
    environment: ${{ github.ref_name == 'live' && 'motivated-patience / production' || 'motivated-patience / staging'}}
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      DATABASE_PUBLIC_URL: ${{ secrets.DATABASE_PUBLIC_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install railway cli
        run: |
          echo "installing railway cli ..."
          npm install -g @railway/cli

      - name: Install dependencies
        run: |
          echo "installing dependencies ..."
          npm ci

      - name: Run Database migrations
        run: |
          echo "running migrations ..."
          npm run migrate

      - name: Deploy to Railway
        run: |
          echo "deploying to railway"
          railway up --service=${{ env.RAILWAY_SERVICE_ID }}

