name: Deploy

on:
  push:
    branches:
      - main
      - staging
      - live

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: wedding_app_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL_TEST: postgresql://user:password@localhost:5432/wedding_app_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Import Base Schema
        run: |
          PGPASSWORD=password psql -h localhost -U user -d wedding_app_test -f schema_dump.sql
        env:
          PGPASSWORD: password

      - name: Run migrations
        run: npm run migrate
        env:
          DATABASE_PUBLIC_URL: postgresql://user:password@localhost:5432/wedding_app_test

      - name: Run tests
        run: |
          npm test
          npm run test:int

  migrations:
    name: Run migrations
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref_name == 'staging' || github.ref_name == 'live'
    environment: ${{ github.ref_name == 'staging' && 'motivated-patience / staging' || github.ref_name == 'live' && 'motivated-patience / production' || '' }}
    env:
      DATABASE_PUBLIC_URL: ${{ secrets.DATABASE_PUBLIC_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npm run migrate
