name: Run migrations

on:
  push:
    branches:
      - staging
      - -live

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'live' && 'production' || 'staging' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Run database migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run migrate
